name: Update

on:
  push:
  schedule:
    - cron: 0 20 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update
      run: |
        rm -f Clash.exe
        Clash=$(wget -qO- https://api.github.com/repos/Fndroid/clash_for_windows_pkg/releases | grep -o '"tag_name": ".*"' | head -n 1 | sed 's/"//g' | sed 's/tag_name: //g')
        wget -N "https://github.com/Fndroid/clash_for_windows_pkg/releases/download/${Clash}/Clash.for.Windows.Setup.${Clash}.exe"
        mv Clash.for.Windows.Setup.${Clash}.exe Clash.exe
        
        rm -f Clash.apk
        ClashA=$(wget -qO- https://api.github.com/repos/Kr328/ClashForAndroid/releases | grep -o '"tag_name": ".*"' | head -n 1 | sed 's/"//g' | sed 's/tag_name: //g')
        wget -N "https://github.com/Kr328/ClashForAndroid/releases/download/${ClashA}/app-premium-universal-release.apk"
        mv app-premium-universal-release.apk Clash.apk
        
        rm -f Clash.dmg
        ClashX=$(wget -qO- https://api.github.com/repos/yichengchen/clashX/releases | grep -o '"tag_name": ".*"' | head -n 1 | sed 's/"//g' | sed 's/tag_name: //g')
        wget -N "https://github.com/yichengchen/clashX/releases/download/${ClashX}/ClashX.dmg"
        mv ClashX.dmg Clash.dmg
        
        rm -f V2Ray.zip
        V2RayN=$(wget -qO- https://api.github.com/repos/2dust/v2rayN/releases | grep -o '"tag_name": ".*"' | head -n 1 | sed 's/"//g' | sed 's/tag_name: //g')
        wget -N "https://github.com/2dust/v2rayN/releases/download/${V2RayN}/v2rayN-Core.zip"
        mv v2rayN-Core.zip V2Ray.zip
        
        rm -f V2Ray.apk
        V2RayNG=$(wget -qO- https://api.github.com/repos/2dust/v2rayNG/releases | grep -o '"tag_name": ".*"' | head -n 1 | sed 's/"//g' | sed 's/tag_name: //g')
        wget -N "https://github.com/2dust/v2rayNG/releases/download/${V2RayNG}/v2rayNG_${V2RayNG}_arm64-v8a.apk"
        mv v2rayNG_${V2RayNG}_arm64-v8a.apk V2Ray.apk
        
        git config --global user.name TCatCloud
        git checkout --orphan latest_branch
        git add -A
        git commit -am "Update"
        git branch -D master
        git branch -m master
        git push -f origin master
